--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

-- Started on 2022-05-07 01:00:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16420)
-- Name: bank_cards; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.bank_cards (
    id integer NOT NULL,
    card_cvc integer,
    card_date timestamp without time zone,
    number_bank_card character varying(255),
    id_user integer
);


ALTER TABLE public.bank_cards OWNER TO scooty;

--
-- TOC entry 213 (class 1259 OID 16419)
-- Name: bank_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.bank_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16414)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO scooty;

--
-- TOC entry 211 (class 1259 OID 16409)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO scooty;

--
-- TOC entry 209 (class 1259 OID 16403)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: scooty
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO scooty;

--
-- TOC entry 210 (class 1259 OID 16404)
-- Name: manufacturer; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.manufacturer (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.manufacturer OWNER TO scooty;

--
-- TOC entry 216 (class 1259 OID 16426)
-- Name: parking_place; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.parking_place (
    id integer NOT NULL,
    latitude double precision,
    longitude double precision,
    radius double precision
);


ALTER TABLE public.parking_place OWNER TO scooty;

--
-- TOC entry 215 (class 1259 OID 16425)
-- Name: parking_place_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.parking_place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parking_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16432)
-- Name: service_history; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.service_history (
    id integer NOT NULL,
    description character varying(255),
    "time" timestamp without time zone,
    id_transport integer
);


ALTER TABLE public.service_history OWNER TO scooty;

--
-- TOC entry 217 (class 1259 OID 16431)
-- Name: service_history_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.service_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16438)
-- Name: transaction; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.transaction (
    id integer NOT NULL,
    operation_time timestamp without time zone,
    sum double precision,
    id_card integer,
    id_travel integer
);


ALTER TABLE public.transaction OWNER TO scooty;

--
-- TOC entry 219 (class 1259 OID 16437)
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16444)
-- Name: transport; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.transport (
    id integer NOT NULL,
    battery_level integer,
    description character varying(255),
    is_free boolean,
    mileage integer,
    name character varying(255),
    manufacturer_id integer,
    id_parking integer,
    qr_code_value character varying(255),
    price integer
);


ALTER TABLE public.transport OWNER TO scooty;

--
-- TOC entry 221 (class 1259 OID 16443)
-- Name: transport_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.transport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16452)
-- Name: travel; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.travel (
    id integer NOT NULL,
    finish_point_latitude double precision,
    finish_point_longitude double precision,
    start_point_latitude double precision,
    start_point_longitude double precision,
    travel_time_start timestamp without time zone,
    travel_time_stop timestamp without time zone,
    card_id integer,
    id_transport integer,
    id_user integer
);


ALTER TABLE public.travel OWNER TO scooty;

--
-- TOC entry 223 (class 1259 OID 16451)
-- Name: travel_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.travel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16458)
-- Name: users; Type: TABLE; Schema: public; Owner: scooty
--

CREATE TABLE public.users (
    id integer NOT NULL,
    birthdate timestamp without time zone,
    confirmed boolean,
    deleted boolean,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    number_driver_license character varying(255),
    number_passport character varying(255),
    password character varying(255),
    phone_number character varying(255),
    series_driver_license character varying(255),
    series_passport character varying(255)
);


ALTER TABLE public.users OWNER TO scooty;

--
-- TOC entry 225 (class 1259 OID 16457)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: scooty
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3380 (class 0 OID 16420)
-- Dependencies: 214
-- Data for Name: bank_cards; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.bank_cards (id, card_cvc, card_date, number_bank_card, id_user) FROM stdin;
\.


--
-- TOC entry 3378 (class 0 OID 16414)
-- Dependencies: 212
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
\.


--
-- TOC entry 3377 (class 0 OID 16409)
-- Dependencies: 211
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- TOC entry 3376 (class 0 OID 16404)
-- Dependencies: 210
-- Data for Name: manufacturer; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.manufacturer (id, title) FROM stdin;
2	sdfsdf
3	hjkghjkh
1	asdasd
\.


--
-- TOC entry 3382 (class 0 OID 16426)
-- Dependencies: 216
-- Data for Name: parking_place; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.parking_place (id, latitude, longitude, radius) FROM stdin;
2	54.758763	32.045012	1
3	54.760931	32.045292	1
4	54.760103	32.046613	1
5	54.708786	32.130477	1
1	54.760129	32.04392	1
\.


--
-- TOC entry 3384 (class 0 OID 16432)
-- Dependencies: 218
-- Data for Name: service_history; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.service_history (id, description, "time", id_transport) FROM stdin;
\.


--
-- TOC entry 3386 (class 0 OID 16438)
-- Dependencies: 220
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.transaction (id, operation_time, sum, id_card, id_travel) FROM stdin;
\.


--
-- TOC entry 3388 (class 0 OID 16444)
-- Dependencies: 222
-- Data for Name: transport; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.transport (id, battery_level, description, is_free, mileage, name, manufacturer_id, id_parking, qr_code_value, price) FROM stdin;
3	73	Худший самокат	t	100	Pro 4	2	3	\N	\N
4	81	Красивый самокат	t	60	Sam	3	4	\N	\N
5	23	Просто самокат	t	21	Parker	1	5	\N	\N
2	54	Лучший самокат	t	170	Robert	2	2	3462345234	\N
\.


--
-- TOC entry 3390 (class 0 OID 16452)
-- Dependencies: 224
-- Data for Name: travel; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.travel (id, finish_point_latitude, finish_point_longitude, start_point_latitude, start_point_longitude, travel_time_start, travel_time_stop, card_id, id_transport, id_user) FROM stdin;
\.


--
-- TOC entry 3392 (class 0 OID 16458)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: scooty
--

COPY public.users (id, birthdate, confirmed, deleted, email, first_name, last_name, middle_name, number_driver_license, number_passport, password, phone_number, series_driver_license, series_passport) FROM stdin;
1	\N	f	f	ignatenkov02@gmail.com	Игнатенков 	Дмитрий 	Владимирович	347658	6362627	1	\N	6654	4742
2	\N	f	f	ignatenkovто02@gmail.com	тчтчь	тстст	таовлал	чтчочо	очовов	лвлвлч	\N	очлвлч	ововоао
\.


--
-- TOC entry 3398 (class 0 OID 0)
-- Dependencies: 213
-- Name: bank_cards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.bank_cards_id_seq', 1, false);


--
-- TOC entry 3399 (class 0 OID 0)
-- Dependencies: 209
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- TOC entry 3400 (class 0 OID 0)
-- Dependencies: 215
-- Name: parking_place_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.parking_place_id_seq', 5, true);


--
-- TOC entry 3401 (class 0 OID 0)
-- Dependencies: 217
-- Name: service_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.service_history_id_seq', 1, false);


--
-- TOC entry 3402 (class 0 OID 0)
-- Dependencies: 219
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.transaction_id_seq', 1, false);


--
-- TOC entry 3403 (class 0 OID 0)
-- Dependencies: 221
-- Name: transport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.transport_id_seq', 1, false);


--
-- TOC entry 3404 (class 0 OID 0)
-- Dependencies: 223
-- Name: travel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.travel_id_seq', 1, false);


--
-- TOC entry 3405 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scooty
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 3212 (class 2606 OID 16424)
-- Name: bank_cards bank_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.bank_cards
    ADD CONSTRAINT bank_cards_pkey PRIMARY KEY (id);


--
-- TOC entry 3210 (class 2606 OID 16413)
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- TOC entry 3208 (class 2606 OID 16408)
-- Name: manufacturer manufacturer_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.manufacturer
    ADD CONSTRAINT manufacturer_pkey PRIMARY KEY (id);


--
-- TOC entry 3214 (class 2606 OID 16430)
-- Name: parking_place parking_place_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.parking_place
    ADD CONSTRAINT parking_place_pkey PRIMARY KEY (id);


--
-- TOC entry 3216 (class 2606 OID 16436)
-- Name: service_history service_history_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.service_history
    ADD CONSTRAINT service_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3218 (class 2606 OID 16442)
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


--
-- TOC entry 3220 (class 2606 OID 16450)
-- Name: transport transport_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT transport_pkey PRIMARY KEY (id);


--
-- TOC entry 3222 (class 2606 OID 16456)
-- Name: travel travel_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.travel
    ADD CONSTRAINT travel_pkey PRIMARY KEY (id);


--
-- TOC entry 3224 (class 2606 OID 16466)
-- Name: users uk_sx468g52bpetvlad2j9y0lptc; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_sx468g52bpetvlad2j9y0lptc UNIQUE (email);


--
-- TOC entry 3226 (class 2606 OID 16464)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3230 (class 2606 OID 16482)
-- Name: transaction fk96cjkgos115mg6imsojf50ex; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fk96cjkgos115mg6imsojf50ex FOREIGN KEY (id_travel) REFERENCES public.travel(id);


--
-- TOC entry 3232 (class 2606 OID 16492)
-- Name: transport fkag2328wggn6kygcxcf5a09ka1; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT fkag2328wggn6kygcxcf5a09ka1 FOREIGN KEY (id_parking) REFERENCES public.parking_place(id);


--
-- TOC entry 3234 (class 2606 OID 16502)
-- Name: travel fkjhm1rtb34rakvwkitl7fl2fh4; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.travel
    ADD CONSTRAINT fkjhm1rtb34rakvwkitl7fl2fh4 FOREIGN KEY (id_transport) REFERENCES public.transport(id);


--
-- TOC entry 3231 (class 2606 OID 16487)
-- Name: transport fknea3amp9bkdjysbiqr69v8h3u; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT fknea3amp9bkdjysbiqr69v8h3u FOREIGN KEY (manufacturer_id) REFERENCES public.manufacturer(id);


--
-- TOC entry 3233 (class 2606 OID 16497)
-- Name: travel fkoaiosmjk517xre30i49dk9hvg; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.travel
    ADD CONSTRAINT fkoaiosmjk517xre30i49dk9hvg FOREIGN KEY (card_id) REFERENCES public.bank_cards(id);


--
-- TOC entry 3235 (class 2606 OID 16507)
-- Name: travel fkogjsgqk8sqnlsqn2ftr2ndw6h; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.travel
    ADD CONSTRAINT fkogjsgqk8sqnlsqn2ftr2ndw6h FOREIGN KEY (id_user) REFERENCES public.users(id);


--
-- TOC entry 3228 (class 2606 OID 16472)
-- Name: service_history fkq4v7khjfc7j6xmamgqkki31om; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.service_history
    ADD CONSTRAINT fkq4v7khjfc7j6xmamgqkki31om FOREIGN KEY (id_transport) REFERENCES public.transport(id);


--
-- TOC entry 3227 (class 2606 OID 16467)
-- Name: bank_cards fkqyu7b13xi2tr45x3l112vwgl6; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.bank_cards
    ADD CONSTRAINT fkqyu7b13xi2tr45x3l112vwgl6 FOREIGN KEY (id_user) REFERENCES public.users(id);


--
-- TOC entry 3229 (class 2606 OID 16477)
-- Name: transaction fkt335pqmpwa8yj5xn9okj8btyl; Type: FK CONSTRAINT; Schema: public; Owner: scooty
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fkt335pqmpwa8yj5xn9okj8btyl FOREIGN KEY (id_card) REFERENCES public.bank_cards(id);


-- Completed on 2022-05-07 01:00:11

--
-- PostgreSQL database dump complete
--

